### ISSUE TITLE
How to MIB file to snmp-notifier?

### ISSUE THREAD

**Issue by honey2156** [maxwo/snmp_notifier#10]
Hi,
In issue https://github.com/maxwo/snmp_notifier/issues/8 , you mentioned that you customized default mib file to provide your own MIB file. In my case I have the MIB file with me, but how to provide that MIB file to snmp-notifier? Where default MIB file is placed in snmp-notifier?

**Comment by maxwo** [comment]
The default MIB has been added in the `mibs/` directory of the repo.

FYI, the SNMP notifier does not need to get any MIB, but the receiver may need one to be able to correctly receive traps.

**Comment by WrzocHoo** [comment]
Unfortunately because of how it is implemented here you WILL NOT be able to prepare valid MIB which will describe this trap with all 3 possible Varbinds (Objects) in neither of SMIv1 nor SMIv2.
NOTIFICATION-TYPE/TRAP-TYPE are leafs in MIB tree, so could not be parents for other nodes, as it is implemented here.
