### ISSUE TITLE
SNMP V3 support

### ISSUE THREAD

**Issue by supraja-grandhi** [maxwo/snmp_notifier#12]
I want to generate SNMPv3 alerts using SNMP Notifier. I am unable to find documentation for the same. Please help me with it.

**Comment by maxwo** [comment]
Hey,
Indeed, SNMP notifier generates V2C traps because this is what was needed when I started the project.
The underlying library (https://github.com/k-sone/snmpgo/) is compatible with SNMP V3, but I haven't been able to test this version, it is therefore not yet available.
Implementation doesn't change that much if you consider the examples:
https://github.com/k-sone/snmpgo/blob/master/examples/trapv2.go
https://github.com/k-sone/snmpgo/blob/master/examples/trapv3.go
What about editing the `connect()` method in `trap_sender.go` and PR it as you can test with a real environment?
