### ISSUE TITLE
SNMP traps retry mechanism

### ISSUE THREAD

**Issue by bmgante** [maxwo/snmp_notifier#186]
Hi
Can someone explain how snmp retries mechanism works on snmp-notifier? If it uses udp how does it know if it should retry to resend the trap or does it somehow works over tcp?
@maxwo could you please provide some further details on this?

--snmp.retries=1

Thanks for any information

**Comment by maxwo** [comment]
Hello,
Basically, the retry is enabled on connection openings (_eg._ DNS error, etc.).
So, indeed, there is no way to tell whether or not a trap is received because it works over UDP.
If you need a way to retry the traps, your best bet is to configure the renotification feature on the alert manager side.
